name: validate data/teachingmaterial.yml

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    name: validate file
    runs-on: ubuntu-latest
    steps:
        
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Install elm and elm-test-rs as defined in elm-tooling.json
      uses: mpizenberg/elm-tooling-action@v1.7

    - name: Create module TeachingMaterialData with teachingMaterialString
      run: ./script_teachingmaterial_yml2elm.sh

    - name: Try parsing teachingMaterialString by running the pseudo-test
      run: elm-test-rs
